- name: Setup rabbitmq
  hosts: node1
  vars_files: ../secrets.yml
  tasks:
  - name: Ensure volume
    docker_volume:
      name: rabbitmq_volume
      state: present
  
  - name: Ensure network
    docker_network:
      name: rabbitmq_network
      driver: overlay
      state: present
  
  - name: Ensure rabbitmq
    docker_swarm_service:
      name: rabbitmq
      image: rabbitmq:3.8.0-beta.3-management-alpine
      hostname: rabbitmq
      constraints:
        - node.labels.rabbitmq == enabled
      publish:
      - published_port: 5672
        target_port: 5672
        mode: host
      - published_port: 15672
        target_port: 15672
        mode: host
      limit_cpu: 1
      limit_memory: 2G
      restart_policy: any
      restart_policy_delay: 20
      restart_policy_attempts: 5
      env:
      - RABBITMQ_DEFAULT_USER={{ rabbitmq_user }}
      - RABBITMQ_DEFAULT_PASS={{ rabbitmq_password}}
      - RABBITMQ_DEFAULT_VHOST=/
      #- RABBITMQ_HIPE_COMPILE=1
      networks:
      - rabbitmq_network
      mounts:
      - type: volume
        source: rabbitmq_volume
        target: /var/lib/rabbitmq