---
- name: Install requirements
  hosts: master:managers:workers
  roles:
    - install_python
    - install_docker

- name: Setup swarm master
  hosts: master
  gather_facts: true
  roles:
    - setup-swarm-master

- name: Setup swarm managers
  hosts: managers
  gather_facts: true
  tasks:
  - name: Join manager {{ ansible_default_ipv4.address }}
    docker_swarm:
      state: join
      advertise_addr: "{{ ansible_default_ipv4.address }}"
      remote_addrs: "{{ hostvars.master.ansible_default_ipv4.address }}"
      join_token: "{{ hostvars.master.manager_token }}"

- name: Setup swarm workers
  hosts: workers
  gather_facts: true
  roles:
    - setup-swarm-workers

# Setup managers
# Setup networks docker_network
# Setup volumes docker_volume