---
- name: Install requirements
  hosts: master:managers:workers
  roles:
    - install_python
    - install_docker

- name: Setup swarm master
  hosts: master
  gather_facts: true
  roles:
    - setup-swarm-master

- name: Setup swarm workers
  hosts: workers
  gather_facts: true
  roles:
    - setup-swarm-workers

# Setup managers
# Setup networks docker_network
# Setup volumes docker_volume